version: '0.1'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"


  django:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery-worker:
    build: ./backend
    command: celery -A config worker -l info -P gevent
    depends_on:
      - django
      - redis

  celery-beat:
    build: ./backend
    command: celery -A config beat
    depends_on:
      - django
      - redis

  react:
    build: .
    ports:
      - '3000:3000'




